### ISSUE TITLE
3/1/17 Lunch!

### ISSUE THREAD

**Issue by matikin9** [matikin9/la-tech-data-food#1]
<img src="https://scontent-lax3-2.cdninstagram.com/t51.2885-15/sh0.08/e35/p750x750/16110325_251944265234575_2518778816210403328_n.jpg" width=300 />

Let's make a group order from Howlin' Ray's for lunch at Grand Park!  It's a super delicious Nashville-style hot fried chicken and the line normally takes at least an hour.  However, with a group order of at least 10 entrees, we can beat the line and pick up our food some time before 11am.

Check out the menu below.  Decide on a spicy level or else I will pick one for you (options range from No-Heat all the way to OMG-do-you-want-to-die?).  I can handle moderately spicy food and Medium is comfortable for me.  They've also got sides, add-ons, drinks, and a dessert option.

<img src="https://cloud.githubusercontent.com/assets/1873072/23226121/51d20ac0-f8e9-11e6-8246-8d84eb44f70a.png" width=600 />

Comment below with your order by 9am, Tuesday 2/28.  Feel free to invite others!

Name | Order | Spicy Level | $$$ Due pre-tax/tip |
-------| -------| -------------| ----------|
Nina Kin | 3 Wings | Medium | $9 |
Hunter Owens | Chicken Sandwich | Medium | $11 |
Juan Lopez | Chicken Sandwich | Hot | $11 |
Leonard Hyman | Chicken Sandwich | Medium | $11 |
Melissa Petersen | Chicken Sandwich, French Fries | Mild | $14 |
Mike Ludwig | Chicken Sandwich | Hot | $11 |
Murriel Perez | Quarter Bird Breast+Wing | Medium | $9 |
Jesse Conde | Chicken Sandwich | Medium | $11 |
Travis Korte | Chicken Sandwich, French Fries | Hot | $14 |
Ev Boyle | Chicken Sandwich, Collard Greens | Medium | $15 |
Lawrence Tang | Batter's Box, Chicken Sandwich | Hot, Howlin' | $43 |

**Comment by hunterowens** [comment]
Hunter Owens | Chicken Sandwich | Medium | $11

**Comment by juan4president** [comment]
Juan Lopez | Chicken Sandwhich | Hot |  $11

_BTW_ this is the greatest idea ever Nina!

**Comment by matikin9** [comment]
@hunterowens @juan4president :sob: we may need to postpone this... we still need 7 more people to sign up!

**Comment by matikin9** [comment]
Leonard Hyman| Chicken Sandwich | Medium | $11

**Comment by matikin9** [comment]
Melissa Petersen l chicken sandwich l mild l French fries l $14

**Comment by MikeLudwig** [comment]
Mike Ludwig | Chicken Sandwhich | Hot | $11

**Comment by matikin9** [comment]
@vykster - if you're interested, we postponed until next wednesday
@murriel - you're in downtown now!  wanna come to grand park for lunch next wednesday?

**Comment by murriel** [comment]
LOVE it - I'm in! Thanks for the invite and I may extend the invite to a couple people if it will help us make it to the minimum order!   
Murriel Perez | Quarter Bird Breast+Wing | Medium | $9

**Comment by 213jec** [comment]
Jesse Conde | chicken sandwich | medium | $11

**Comment by traviskorte** [comment]
Travis Korte | chicken sandwich, french fries | hot | $14

**Comment by matikin9** [comment]
@rayidghani from @hunterowens you should get in on this this.

**Comment by evboyle** [comment]
If it's not too late to sign up, I'm in!

Ev Boyle | Chicken Sandwich (Medium) + Collard Greens | $15

**Comment by matikin9** [comment]
@hunterowens @juan4president @lhyman @melpete @MikeLudwig @murriel @213jec @traviskorte @evboyle 

yay everyone, we made it to 10 orders!  :laughing:   i'll put in the order tomorrow morning at 9am.  Note: chicken pickup is at 11am Wednesday so let's shoot for a slightly earlier 11:30am lunch at Grand Park.  If it's your first time, we usually sit at the upper part of the performance lawn, between Hill and Grand.

**Comment by matikin9** [comment]
Success!  Thank you everyone for participating!  Have another idea for our Wednesday lunches?  Let me know!
